### ISSUE TITLE
【EXTERNAL SOURCES】左下角 + 号功能有问题

### ISSUE THREAD

**Issue by ferocknew** [oulvhai/MWeb-Themes#1]
点击

```
+ New Floder
```

无反应
-  如图

![qq20150517-1 2x](https://cloud.githubusercontent.com/assets/2178683/7670531/1ac783f4-fcdb-11e4-9eda-bc25bdae7c09.png)

**Comment by oimotis** [comment]
已确认，并修正。感谢！
